### ISSUE TITLE
Add "Refund" button to the charge detail page

### ISSUE THREAD

**Issue by ctroms** [tighten/nova-stripe#13]
### Expected Behavior

Add a "Refund" button to the charge detail page

**Comment by packytagliaferro** [comment]
Is there any update on this? My app only does single charges so it would be nice for an admin to be able to refund from Nova. I dont want to give all admins access to the actual Stripe dashboard to refund.

**Comment by mattstauffer** [comment]
Update: Hoping someone picks it up for Hacktoberfest :D
