### ISSUE TITLE
Nova 4.0 Support?

### ISSUE THREAD

**Issue by gbrits** [tighten/nova-stripe#43]
Hi will this package be updated to work with the new Nova 4.0? I have noticed it has a similar abstract class issue as other Nova 3.0 packages at the moment.

**Comment by faxblaster** [comment]
Hi @gbrits - thanks for asking! Yep, that update is in the works!

**Comment by faxblaster** [comment]
Hey @gbrits - [v2.0.0](https://github.com/tighten/nova-stripe/releases/tag/v2.0.0) w/Nova 4 support is up (finally! 😅)
