### ISSUE TITLE
Class Tighten\NovaStripe\NovaStripe contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Laravel\Nova\Tool::menu)

### ISSUE THREAD

**Issue by AkhilTreblle** [tighten/nova-stripe#44]
Why am getting this on nova 4 ?

**Comment by faxblaster** [comment]
Hey @AkhilTreblle! Sorry for the delay. Took me a little while to get around to this upgrade, but this issue should be solved if you upgrade to [v2.*](https://github.com/tighten/nova-stripe/releases/tag/v2.0.0). 

I'm gonna close this issue, but drop a line if you run into any issues. Thanks for using the package!

**Comment by dsingh09** [comment]
Problem 1
    - tightenco/nova-stripe[v2.0.0, ..., v2.0.1] require php ^8.0|^8.1 -> your php version (7.4.24) does not satisfy that requirement.
    - Root composer.json requires tightenco/nova-stripe ^2.0.0 -> satisfiable by tightenco/nova-stripe[v2.0.0, v2.0.1].

**Comment by faxblaster** [comment]
@dsingh09 - v2.0.2 adds back PHP 7.4 support 🙌
