### ISSUE TITLE
Unable to cache routes

### ISSUE THREAD

**Issue by tominon** [tighten/nova-stripe#54]
There are two routes with the same name "nova-stripe.customers" which causes error when trying to cache routes via artisan command `route:cache`:

> Unable to prepare route [nova/nova-stripe/customers/{customerId}] for serialization. Another route has already been assigned name [nova-stripe.customers]

**Comment by faxblaster** [comment]
Thanks for opening this issue, @tominon! Fixed in v2.0.3 🙌
