### ISSUE TITLE
Nova 3 support for Customer Information

### ISSUE THREAD

**Issue by chx2** [tighten/nova-stripe#56]
Hello, I gave this package a try and loving it currently! 

One detail that I noticed working with a license in Nova 3 is the customer views shown in the README are only available in version 2 or newer, which requires Nova 4. I noticed the issues they were introduced in https://github.com/tighten/nova-stripe/pull/33 and https://github.com/tighten/nova-stripe/pull/36 were actually before the Nova 4 changes were made but there isn't a tagged version until after the v2 release.

I was wondering if it would be possible to get another tagged v1 release up to before https://github.com/tighten/nova-stripe/pull/45 if it would be possible? I don't know if there's much interest but stumbled across[ this Laracasts thread](https://laracasts.com/discuss/channels/nova/method-router-does-not-exist) beforehand, so there's at least one other person out there who might have interest 😅 

Thank you!

**Comment by faxblaster** [comment]
@chx2 - Great point, thank you! I'll try to get this tagged in the next day or so.

**Comment by faxblaster** [comment]
Closed by [v1.1.0](https://packagist.org/packages/tightenco/nova-stripe#v1.1.0)
