### ISSUE TITLE
Custom nova path

### ISSUE THREAD

**Issue by freasy** [tighten/nova-stripe#61]
We have configured a custom nova path `/admin` but `ChargesTable.vue` is hardcoded to `/nova`

```vue
<InertiaLink
    :href="`/nova/nova-stripe/charges/${charge.id}`"
    :aria-label="__('View')"
>
    <HeroiconsOutlineEye />
</InertiaLink>
```

**Comment by faxblaster** [comment]
Hey @freasy thanks for opening the issue! This is resolved in v2.0.5, and will use the `path` value from your nova config file. 🙌
