### ISSUE TITLE
View Link Incorrect on Customers Table When Nova At Root Path

### ISSUE THREAD

**Issue by brandonjbegle** [tighten/nova-stripe#63]
I'm not sure why, but when Nova is at the root path, the View Link appears as /customers/${customer.id} without the /nova-stripe/ portion. Anyone have an idea why?

`<InertiaLink
                                :href="`${novaPath}/nova-stripe/customers/${customer.id}`"
                                :aria-label="__('View')"
                            >`

Upon further testing, it's when the nova path is set to '/' vs an empty string. Seems that InertiaLink interprets two consecutive forward slashes as skipping a directory. Not sure if it's worth putting a check on the Nova path for this case or not, but that appears to be the cause.

You end up with //nova-stripe/customers/${customer.id} (InertiaLink converts to /customers/${customer.id})
vs
/nova-stripe/customers/${customer.id}

**Comment by faxblaster** [comment]
Thanks so much for opening the issue @brandonjbegle, and providing the additional context 🙏. I 100% think it's worth checking for and will shoot for having a new release with this fix out today.
