### ISSUE TITLE
Changing the resource name from stripe to something else

### ISSUE THREAD

**Issue by sdebarun** [tighten/nova-stripe#7]
I am looking for a way to change the Resource aname from **STRIPE** in nova dashborad to something different. I do not want to change the chane it in the package files directly in vendor directory. So far I have found nothing to acheive so. Can you guide me to do it? 

I am not sure if it is a issue but not finding any other place to ask this so posting here. If this is not the place let me know the place where I can ask and get answer.

**Comment by bakerkretzmar** [comment]
@sdebarun if you just want to change the text displayed in Nova's sidebar, copy this package's `resources/views/navigation.blade.php` into your app at `resources/views/vendor/nova-stripe/navigation.blade.php` and update it to display whatever you'd like.

**Comment by mattstauffer** [comment]
Thanks @bakerkretzmar!
